name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'product/**'
      - 'kubernetes/**'
      - '.github/workflows/ci-cd.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: product-service
      IMAGE_TAG: v1.0.0-${{ github.run_number }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG ./product
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG_DATA" | base64 -d > ~/.kube/config

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/product-service-v1 product-service=$DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG -n default

      - name: Wait for Deployment Rollout
        run: |
          kubectl rollout status deployment/product-service-v1 -n default
